name: ExtraFlags
main: com.chromaclypse.extraflags.ExtraFlags
version: ${project.version}
description: Extra (elytra) wg flags
author: ezeiger92
api-version: 1.13
depend: [WorldGuard]
commands: {}
permissions: {}